site_name: The Art of Conversation Marketing Handbook
site_description: Brando BDV is the world’s first Brand Definition Vocabulary for structuring brand identity, tone, and integrity for the AI Web.
site_author: Jonathan Bowker
site_url: https://conversationmarketing.advancedanalytica.co.uk
repo_url: https://github.com/JonathanBowker/conversation-marketing
repo_name: JonathanBowker/conversation-marketing

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.webp
  favicon: assets/images/favicon.svg
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.headings.anchor
    - header.autohide
  language: en

plugins:
  - search
  - tags
  - copy-well-known

extra:
  static_dirs:
    - bdv-terms/data
  include:
    - data/brando-schema.json
  meta_defaults:
    keywords: brando, brand definition language, bdl, brand schema, ai brand safety, structured branding, LLM prompts, AI web, semantic brand metadata, tone of voice schema
    og_title: Brando – The Brand Definition Language for the AI Web
    og_description: Brando is a machine-readable Brand Definition Language (BDL) that protects and structures brand identity in the AI era.
    og_url: https://brandoschema.com/bdl/
    og_image: https://brandoschema.com/assets/images/brando-og-image.png
    twitter_card: summary_large_image
    twitter_title: Brando – Brand Definition Language (BDL)
    twitter_description: Structure your brand identity, tone, and values for intelligent agents and LLMs with Brando BDL.
    twitter_image: https://brandoschema.com/assets/images/brando-og-image.png
  custom_cta: true

extra_css:
  - css/custom.css
  - css/styles.css

extra_javascript:
  - js/smooth-scroll.js
  - https://d3js.org/d3.v7.min.js
  - js/linked_map.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.extra

nav:
  - Overview: index.md
  - Old vs New: old-vs-new.md
  - Why Now?: why-now.md
  - The Core Philosophy: core-philosophy.md
  - How to Use This Book: how-to-use.md

  - "Part 1: The Foundational Rules – Strategy & Principles":
      - "Rule #1: From Monologue to Dialogue": part1/rule-1-monologue-to-dialogue.md
      - "Rule #2: Know Your Audience with AI-Powered Personas": part1/rule-2-ai-personas.md
      - "Rule #3: Define Your Conversational Purpose": part1/rule-3-purpose.md
      - "Rule #4: Be Where the Conversation Is": part1/rule-4-channels.md

  - "Part 2: The Playbook – Design & Implementation":
      - Designing Intuitive Conversation Flows: part2/conversation-flows.md
      - "Fueling Your Engine: Content for Conversation": part2/content-for-conversation.md
      - "The Tech Stack: Tools of the Modern Marketer": part2/tech-stack.md
      - Launching Your Conversational Engine: part2/launching.md

  - "Part 3: Advanced Applications & Growth":
      - "The Proactive Play: Initiating a Valuable Dialogue": part3/proactive-dialogue.md
      - Brand Dialogue Engineering: part3/brand-dialogue-engineering.md
      - Mastering Conversational Advertising: part3/conversational-advertising.md
      - "Conversational Sales: From Lead to Loyal Customer": part3/conversational-sales.md

  - "Part 4: The Rules of Measurement & The Future":
      - "The New ROI: Measuring What Matters": part4/new-roi.md
      - The Rule of Continuous Improvement: part4/continuous-improvement.md
      - "The Future Rules: What's Next on the Horizon": part4/future-rules.md

  - Conclusion: conclusion.md

  - Appendix:
      - Glossary: appendix/glossary.md
      - Resource Guide: appendix/resources.md
      - Conversation Flow Template: appendix/conversation-template.md
      - Conversation Engine Checklist: appendix/checklist.md

  - About Us:
      - Advanced Analytica: about.md
      - Terms of Service: terms-of-service.md
